import { type RatingKeyModel } from '#lib-shared/funding/funding.models';

export enum RATING_KEY {
  A = 'A',
  AA = 'AA',
  AAA = 'AAA',
  AAm = 'AA-',
  AAp = 'AA+',
  Am = 'A-',
  Ap = 'A+',
  B = 'B',
  BB = 'BB',
  BBB = 'BBB',
  BBBm = 'BBB-',
  BBBp = 'BBB+',
  BBm = 'BB-',
  BBp = 'BB+',
  Bm = 'B-',
  Bp = 'B+',
  CCC = 'CCC',
  CCCm = 'CCC-',
  CCCp = 'CCC+',
  D = 'D',
}

export const RATING_KEY_RANK: Record<RatingKeyModel, number> = {
  [RATING_KEY.AAA]: 1,
  [RATING_KEY.AAp]: 2,
  [RATING_KEY.AA]: 3,
  [RATING_KEY.AAm]: 4,
  [RATING_KEY.Ap]: 5,
  [RATING_KEY.A]: 6,
  [RATING_KEY.Am]: 7,
  [RATING_KEY.BBBp]: 8,
  [RATING_KEY.BBB]: 9,
  [RATING_KEY.BBBm]: 10,
  [RATING_KEY.BBp]: 11,
  [RATING_KEY.BB]: 12,
  [RATING_KEY.BBm]: 13,
  [RATING_KEY.Bp]: 14,
  [RATING_KEY.B]: 15,
  [RATING_KEY.Bm]: 16,
  [RATING_KEY.CCCp]: 17,
  [RATING_KEY.CCC]: 18,
  [RATING_KEY.CCCm]: 19,
  [RATING_KEY.D]: 20,
};
