packages:
  - packages/*

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@firebase/util'
  - '@parcel/watcher'
  - '@swc/core'
  - aws-sdk
  - core-js
  - dooboolab-welcome
  - esbuild
  - mongodb-memory-server
  - protobufjs
  - puppeteer
  - serverless
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd

patchedDependencies:
  vite-plugin-checker@0.10.3: patches/vite-plugin-checker@0.10.3.patch
