packages:
  - packages/*
ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@firebase/util'
  - '@parcel/watcher'
  - '@swc/core'
  - aws-sdk
  - core-js
  - dooboolab-welcome
  - esbuild
  - mongodb-memory-server
  - protobufjs
  - puppeteer
  - serverless
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd
overrides:
  app: 'link:'
patchedDependencies:
  vite-plugin-checker@0.9.2: patches/vite-plugin-checker@0.9.2.patch
