packages:
  - packages/*

allowBuilds:
  '@apollo/protobufjs': true
  '@ffmpeg-installer/darwin-arm64': true
  '@firebase/util': true
  '@parcel/watcher': true
  '@swc/core': true
  aws-crt: true
  aws-sdk: true
  azure-functions-core-tools: false
  core-js: true
  cpu-features: true
  dooboolab-welcome: true
  esbuild: true
  keytar: true
  mongodb-memory-server: true
  protobufjs: true
  puppeteer: true
  serverless: true
  spawn-sync: true
  ssh2: true
  unrs-resolver: true

allowUnusedPatches: true

shamefullyHoist: true

hoistPattern:
  - '*'

patchedDependencies:
  react-native-screens: patches/react-native-screens.patch
