export const ACCESS_RESOURCE_NAME = 'Access';

export enum ACCESS_ROLE {
  ADMIN = 'ADMIN',
  ANY = 'ANY',
  USER = 'USER',
}

export enum ACCESS_LEVEL {
  PROHIBITED = 'PROHIBITED',
  PROTECTED = 'PROTECTED',
  PUBLIC = 'PUBLIC',
  RESTRICTED = 'RESTRICTED',
}
