# generated by datamodel-codegen:
#   filename:  Utility.json
#   timestamp: 2025-06-26T02:34:32+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Extra, Field


class UtilityTypeModel(Enum):
    AUTHENTICATION = 'authentication'
    DATABASE = 'database'
    FUNCTION = 'function'
    HOSTING = 'hosting'
    PAYMENT = 'payment'
    SMS = 'sms'
    SMTP = 'smtp'
    USAGE = 'usage'


class UtilityModel(BaseModel):
    class Config:
        extra = Extra.forbid

    description: Optional[str] = None
    imageSrc: Optional[str] = None
    name: str
    pricing: Optional[str] = None
    type: List[UtilityTypeModel]
    url: Optional[str] = None
    field_id: str = Field(..., alias='_id')
    beforeCreate: None = None
    created: datetime
    isFixture: Optional[bool] = None


class Model(BaseModel):
    __root__: UtilityModel
