[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
force_grid_wrap = 0
line_length = 100
include_trailing_comma = true
profile = "black"

[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax", "Unpack"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.poetry]
name = "lib-ai"
description = ""
version = "0.0.1"
license = "MIT"
authors = ["YG Min <ygmindev@gmail.com>"]
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
lib_config = {path="../lib-config-py", develop=true}
lib_shared = {path="../lib-shared-py", develop=true}
python = "3.12.7"
numpy = "^2.1.1"
scikit-learn = "^1.5.2"
polars = "^1.8.2"
torch = "^2.5.1"
torchvision = "^0.20.1"
torchaudio = "^2.5.1"
torcheval = "^0.0.7"
kaggle = "^1.6.17"
pydash = "^8.0.4"
xgboost = "^2.1.2"
hyperopt = "^0.2.7"
transformers = "^4.46.2"
datasets = "^3.1.0"
sentence-transformers = "^3.3.0"
accelerate = "^1.1.1"
evaluate = "^0.4.3"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
mypy = "^1.11.2"
isort = "^5.13.2"
flake8 = "^7.1.1"
pylint = "^3.3.1"
autoflake = "^2.3.1"
tqdm = "^4.67.0"
