[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
force_grid_wrap = 0
line_length = 100
include_trailing_comma = true
profile = "black"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.poetry]
name = "lib-ai"
description = ""
version = "0.0.1"
license = "MIT"
authors = ["YG Min <ygmindev@gmail.com>"]
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
python = "3.12.6"
