[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
force_grid_wrap = 0
line_length = 100
include_trailing_comma = true
profile = "black"

[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax", "Unpack"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.poetry]
name = "lib-config"
description = ""
version = "0.0.1"
license = "MIT"
authors = ["YG Min <ygmindev@gmail.com>"]
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
python = "3.12.7"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
mypy = "^1.11.2"
isort = "^5.13.2"
flake8 = "^7.1.1"
pylint = "^3.3.1"
autoflake = "^2.3.1"
