[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
force_grid_wrap = 0
line_length = 100
include_trailing_comma = true
profile = "black"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.poetry]
name = "lib-shared"
description = ""
version = "0.0.1"
license = "MIT"
authors = ["YG Min <ygmindev@gmail.com>"]
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
python = "3.12.6"
numpy = "1.26.4"
pydash = "^8.0.4"
python-dotenv = "^1.1.1"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
isort = "^5.13.2"
flake8 = "^7.1.1"
pylint = "3.3.3"
autoflake = "^2.3.1"
tqdm = "^4.67.0"
