[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
force_grid_wrap = 0
line_length = 100
include_trailing_comma = true
profile = "black"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.poetry]
name = "service-server"
description = ""
version = "0.0.1"
license = "MIT"
authors = ["YG Min <ygmindev@gmail.com>"]
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
lib_ai = {path="../lib-ai-py", develop=true}
lib_config = {path="../lib-config-py", develop=true}
lib_model = {path="../lib-model-py", develop=true}
lib_shared = {path="../lib-shared-py", develop=true}
lib_quant = {path="../lib-quant-py", develop=true}
python = "3.12.6"
transformers = "^4.46.3"
torch = "^2.5.1"
torchvision = "^0.20.1"
torchaudio = "^2.5.1"
torcheval = "^0.0.7"
numpy = "1.26.4"
polars = "^1.7.1"
scikit-learn = "^1.5.2"
kaggle = "^1.6.17"
pydash = "^8.0.4"
xgboost = "^2.1.2"
hyperopt = "^0.2.7"
datasets = "^3.1.0"
sentence-transformers = "^3.3.0"
accelerate = "^1.1.1"
evaluate = "^0.4.3"
tqdm = "^4.67.1"
faiss-cpu = "^1.9.0.post1"
langchain = "^0.3.12"
langchain-community = "^0.3.12"
flask = "^3.1.1"
dspy-ai = "^2.6.27"
pydantic = "^2.11.7"
beanie = "^2.0.0"
requests = "^2.32.4"
datamodel-code-generator = "^0.31.2"
python-dotenv = "^1.1.1"
motor = "^3.7.1"
beautifulsoup4 = "^4.13.4"
httpx = "^0.28.1"
lxml = "^6.0.0"
attr = "^0.3.2"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
isort = "^5.13.2"
pytest-cov = "^5.0.0"
pytest = "^8.3.3"
flake8 = "^7.1.1"
pylint = "3.3.3"
autoflake = "^2.3.1"
tqdm = "^4.67.0"
ollama = "^0.4.1"
mlx-lm = "^0.20.1"
ruff = "^0.12.4"
