# generated by datamodel-codegen:
#   filename:  y.json
#   timestamp: 2025-06-28T02:27:51+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class YModel(BaseModel):
    class Config:
        extra = Extra.allow

    y1: float
    y2: str


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: YModel
