import { type TestableRelatedResourceImplementationModel } from '@lib/model/test/TestableRelatedResource/TestableRelatedResourceImplementation/TestableRelatedResourceImplementation.models';

export type UseTestableRelatedResourceResourceModel = TestableRelatedResourceImplementationModel;
