%YAML 1.1
---
name: Local Config
version: 1.0.0
schema: v1
open_router: &open_router
  provider: openrouter
  apiBase: https://openrouter.ai/api/v1
  apiKey: ${{ secrets.OPENAI_API_KEY }}
ollama: &ollama
  provider: ollama
models:
  - name: NVIDIA Nemotron 3 Ultra (Chat)
    <<: *open_router
    model: nvidia/nemotron-3-ultra-550b-a55b:free
    roles:
      - chat
      - edit
      - apply
  - name: Qwen 2.5 Coder
    <<: *ollama
    model: qwen2.5-coder:1.5b
    roles:
      - autocomplete
    autocompleteOptions:
      debounceDelay: 350
      maxPromptTokens: 2048
      multilineCompletions: "always"
