name: Local Config
version: 0.0.1
models:
  - name: NVIDIA Nemotron 3 Ultra (Chat)
    provider: openrouter
    model: nvidia/nemotron-3-ultra-550b-a55b:free
    apiBase: https://openrouter.ai/api/v1
    apiKey: ${{ secrets.OPENAI_API_KEY }}
    roles:
      - chat
      - edit
      - apply
  - name: NVIDIA Nemotron 3 Ultra (Autocomplete)
    provider: openrouter
    model: nvidia/nemotron-3-ultra-550b-a55b:free
    apiBase: https://openrouter.ai/api/v1
    apiKey: ${{ secrets.OPENAI_API_KEY }}
    roles:
      - autocomplete
    autocompleteOptions:
      debounceDelay: 350
      maxPromptTokens: 1024
      multilineCompletions: "always"
