name: Local Config
version: 0.0.1
models:
  - name: NVIDIA Nemotron 3 Ultra (Chat)
    provider: openrouter
    model: nvidia/nemotron-3-ultra-550b-a55b:free
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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
    roles:
      - chat
      - edit
      - apply
  - name: NVIDIA Nemotron 3 Ultra (Autocomplete)
    provider: openrouter
    model: nvidia/nemotron-3-ultra-550b-a55b:free
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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
    roles:
      - autocomplete
    autocompleteOptions:
      debounceDelay: 350
      maxPromptTokens: 1024
      multilineCompletions: "always"
