from lib_ai.transform.utils.transformer.min_max_scaler_transformer._min_max_scaler_transformer import _MinMaxScalerTransformer
from lib_ai.transform.utils.transformer.min_max_scaler_transformer.min_max_scaler_transformer_models import MinMaxScalerTransformerModel


class MinMaxScalerTransformer(_MinMaxScalerTransformer, MinMaxScalerTransformerModel):
    pass
