from typing import Any, Protocol


class _LoggerModel(Protocol):
    def __init__(self) -> None: ...

    def debug(self, message: Any) -> None: ...

    def error(self, message: Any) -> None: ...

    def info(self, message: Any) -> None: ...
