from typing import Protocol, Self


class _LoggerModel(Protocol):
    def __init__(self) -> None: ...

    def debug(self: Self, message: str) -> None: ...

    def error(self: Self, message: str) -> None: ...

    def info(self: Self, message: str) -> None: ...
