[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
force_grid_wrap = 0
line_length = 100
include_trailing_comma = true
profile = "black" 

[tool.poetry]
name = "service-ai"
description = ""
version = "0.0.1"
license = "MIT"
authors = ["YG Min <ygmindev@gmail.com>"]
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
lib_shared = {path="../lib-shared-py/src", develop=true}
python = "~3.12"
transformers = "^4.44.2"
torch = "^2.4.0"
torchvision = "^0.19.0"
torchaudio = "^2.4.0"
accelerate = "^0.33.0"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
isort = "^5.13.2"
mypy = "^1.11.2"
pytest-cov = "^5.0.0"
pytest = "^8.3.2"
