import { type InterestRateFutureQuoteImplementationModel } from '@lib/model/quant/InterestRateFutureQuote/InterestRateFutureQuoteImplementation/InterestRateFutureQuoteImplementation.models';

export type UseInterestRateFutureQuoteResourceModel = InterestRateFutureQuoteImplementationModel;
