jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: sign in
        uses: docker/login-action@v2
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: run ratesUpload
        run: docker run --rm ghcr.io/ygmindev/service-job-js
          /Users/yoongeemin/Developer/Projects/app/packages/service-job-js/__dist__/ratesUpload
name: ratesUpload
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
