jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: sign in
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USERNAME }}
      - name: run ratesUpload
        run: docker run --rm ghcr.io/ygmindev/service-job-js ratesUpload
name: ratesUpload
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
