export enum IONICON_ICON {
  add = 'add',
  alarm = 'alarm',
  analytics = 'analytics',
  app = 'app',
  arrowIn = 'arrowIn',
  arrowLeft = 'arrowLeft',
  arrowOut = 'arrowOut',
  arrowRight = 'arrowRight',
  arrowUp = 'arrowUp',
  arrowUpCircle = 'arrowUpCircle',
  attach = 'attach',
  bar = 'bar',
  book = 'book',
  bookmark = 'bookmark',
  briefcase = 'briefcase',
  bucket = 'bucket',
  bug = 'bug',
  building = 'building',
  calculator = 'calculator',
  calendar = 'calendar',
  camera = 'camera',
  card = 'card',
  cash = 'cash',
  chat = 'chat',
  chats = 'chats',
  check = 'check',
  checkCircle = 'checkCircle',
  chevronDown = 'chevronDown',
  chevronLeft = 'chevronLeft',
  chevronRight = 'chevronRight',
  chevronUp = 'chevronUp',
  chip = 'chip',
  cloud = 'cloud',
  contrast = 'contrast',
  cube = 'cube',
  dark = 'dark',
  dashboard = 'dashboard',
  developer = 'developer',
  document = 'document',
  ear = 'ear',
  edit = 'edit',
  ellipsis = 'ellipsis',
  ellipsisVertical = 'ellipsisVertical',
  email = 'email',
  exclamationCircle = 'exclamationCircle',
  eye = 'eye',
  eyeOff = 'eyeOff',
  fingerprint = 'fingerprint',
  git = 'git',
  globe = 'globe',
  hand = 'hand',
  happy = 'happy',
  home = 'home',
  image = 'image',
  info = 'info',
  internet = 'internet',
  invest = 'invest',
  light = 'light',
  location = 'location',
  lock = 'lock',
  menu = 'menu',
  notifications = 'notifications',
  offline = 'offline',
  people = 'people',
  person = 'person',
  phone = 'phone',
  pie = 'pie',
  preferences = 'preferences',
  question = 'question',
  refresh = 'refresh',
  repeat = 'repeat',
  return = 'return',
  sad = 'sad',
  save = 'save',
  scissor = 'scissor',
  search = 'search',
  send = 'send',
  server = 'server',
  settings = 'settings',
  shield = 'shield',
  signout = 'signout',
  skill = 'skill',
  smile = 'smile',
  star = 'star',
  starBlank = 'starBlank',
  switch = 'switch',
  thunder = 'thunder',
  time = 'time',
  times = 'times',
  timesCircle = 'timesCircle',
  trash = 'trash',
  undo = 'undo',
  upload = 'upload',
  wallet = 'wallet',
}

export enum FONTAWESOME_ICON {
  bank = 'bank',
  contact = 'contact',
  copyright = 'copyright',
  diamond = 'diamond',
  dollar = 'dollar',
  id = 'id',
}

export const IONIC_ICONS: Record<IONICON_ICON, string> = {
  add: 'add-circle-outline',
  alarm: 'alarm-outline',
  analytics: 'analytics-outline',
  app: 'extension-puzzle-outline',
  arrowIn: 'return-down-back-outline',
  arrowLeft: 'arrow-back-outline',
  arrowOut: 'return-up-forward-outline',
  arrowRight: 'arrow-forward-outline',
  arrowUp: 'arrow-up-outline',
  arrowUpCircle: 'arrow-up-circle-outline',
  attach: 'attach-outline',
  bar: 'bar-chart-outline',
  book: 'book-outline',
  bookmark: 'bookmark-outline',
  briefcase: 'briefcase-outline',
  bucket: 'color-fill-outline',
  bug: 'bug-outline',
  building: 'business-outline',
  calculator: 'calculator-outline',
  calendar: 'calendar-outline',
  camera: 'camera-outline',
  card: 'card-outline',
  cash: 'cash-outline',
  chat: 'chatbox-outline',
  chats: 'chatbubbles-outline',
  check: 'checkmark-outline',
  checkCircle: 'checkmark-circle-outline',
  chevronDown: 'chevron-down-outline',
  chevronLeft: 'chevron-back-outline',
  chevronRight: 'chevron-forward-outline',
  chevronUp: 'chevron-up-outline',
  chip: 'hardware-chip-outline',
  cloud: 'cloud-outline',
  contrast: 'contrast',
  cube: 'cube-outline',
  dark: 'moon',
  dashboard: 'grid-outline',
  developer: 'terminal-outline',
  document: 'document-text-outline',
  ear: 'ear-outline',
  edit: 'create-outline',
  ellipsis: 'ellipsis-horizontal',
  ellipsisVertical: 'ellipsis-vertical',
  email: 'mail-outline',
  exclamationCircle: 'alert-circle-outline',
  eye: 'eye-outline',
  eyeOff: 'eye-off-outline',
  fingerprint: 'finger-print-outline',
  git: 'git-branch-outline',
  globe: 'globe-outline',
  hand: 'hand-left-outline',
  happy: 'happy-outline',
  home: 'home-outline',
  image: 'image-outline',
  info: 'information-circle',
  internet: 'wifi-outline',
  invest: 'trending-up-outline',
  light: 'sunny-outline',
  location: 'location-outline',
  lock: 'lock-closed-outline',
  menu: 'menu-outline',
  notifications: 'notifications-outline',
  offline: 'cloud-offline-outline',
  people: 'people-circle-outline',
  person: 'person-circle-outline',
  phone: 'call-outline',
  pie: 'pie-chart-outline',
  preferences: 'options-outline',
  question: 'help-outline',
  refresh: 'refresh-outline',
  repeat: 'repeat-outline',
  return: 'return-down-back-outline',
  sad: 'sad-outline',
  save: 'save-outline',
  scissor: 'cut-outline',
  search: 'search-outline',
  send: 'send-outline',
  server: 'server-outline',
  settings: 'settings-outline',
  shield: 'shield-outline',
  signout: 'log-out-outline',
  skill: 'medal-outline',
  smile: 'happy-outline',
  star: 'star',
  starBlank: 'star-outline',
  switch: 'toggle-outline',
  thunder: 'flash-outline',
  time: 'time-outline',
  times: 'close-outline',
  timesCircle: 'close-circle-outline',
  trash: 'trash-bin-outline',
  undo: 'arrow-undo-outline',
  upload: 'cloud-upload-outline',
  wallet: 'wallet-outline',
};

export const FONTAWESOME_ICONS: Record<FONTAWESOME_ICON, string> = {
  bank: 'bank',
  contact: 'address-book-o',
  copyright: 'copyright',
  diamond: 'diamond',
  dollar: 'dollar',
  id: 'id-card-o',
};
