export const IONIC_ICONS = {
  add: 'add-circle-outline',
  alarm: 'alarm-outline',
  analytics: 'analytics-outline',
  arrowIn: 'return-down-back-outline',
  arrowLeft: 'arrow-back-outline',
  arrowOut: 'return-up-forward-outline',
  arrowRight: 'arrow-forward-outline',
  arrowUp: 'arrow-up-outline',
  arrowUpCircle: 'arrow-up-circle-outline',
  attach: 'attach-outline',
  bar: 'bar-chart-outline',
  book: 'book-outline',
  bookmark: 'bookmark-outline',
  briefcase: 'briefcase-outline',
  bucket: 'color-fill-outline',
  bug: 'bug-outline',
  building: 'business-outline',
  calculator: 'calculator-outline',
  calendar: 'calendar-outline',
  camera: 'camera-outline',
  card: 'card-outline',
  cash: 'cash-outline',
  chat: 'chatbox-outline',
  chats: 'chatbubbles-outline',
  check: 'checkmark-outline',
  checkCircle: 'checkmark-circle-outline',
  chevronDown: 'chevron-down-outline',
  chevronLeft: 'chevron-back-circle-outline',
  chevronRight: 'chevron-forward-circle-outline',
  chevronUp: 'chevron-up-outline',
  chip: 'hardware-chip-outline',
  cloud: 'cloud-outline',
  code: 'code-slash-outline',
  contrast: 'contrast-outline',
  cube: 'cube-outline',
  dark: 'moon',
  dashboard: 'grid-outline',
  developer: 'terminal-outline',
  document: 'document-text-outline',
  ear: 'ear-outline',
  edit: 'create-outline',
  ellipsis: 'ellipsis-horizontal',
  ellipsisVertical: 'ellipsis-vertical',
  email: 'mail-outline',
  exclamationCircle: 'alert-circle-outline',
  eye: 'eye-outline',
  eyeOff: 'eye-off-outline',
  fingerprint: 'finger-print-outline',
  git: 'git-branch-outline',
  globe: 'globe-outline',
  hand: 'hand-left-outline',
  happy: 'happy-outline',
  home: 'home-outline',
  image: 'image-outline',
  info: 'information-circle',
  internet: 'wifi-outline',
  invest: 'trending-up-outline',
  light: 'sunny-outline',
  location: 'location-outline',
  lock: 'lock-closed-outline',
  menu: 'menu-outline',
  notifications: 'notifications-outline',
  offline: 'cloud-offline-outline',
  people: 'people-circle-outline',
  person: 'person-outline',
  personCircle: 'person-circle-outline',
  phone: 'call-outline',
  pie: 'pie-chart-outline',
  preferences: 'options-outline',
  question: 'help-outline',
  refresh: 'refresh-outline',
  repeat: 'repeat-outline',
  return: 'return-down-back-outline',
  sad: 'sad-outline',
  save: 'save-outline',
  scissor: 'cut-outline',
  search: 'search-outline',
  send: 'send-outline',
  server: 'server-outline',
  settings: 'settings-outline',
  shield: 'shield-outline',
  signin: 'log-in-outline',
  signout: 'log-out-outline',
  skill: 'medal-outline',
  smile: 'happy-outline',
  star: 'star',
  starBlank: 'star-outline',
  switch: 'toggle-outline',
  thunder: 'flash-outline',
  time: 'time-outline',
  times: 'close-outline',
  timesCircle: 'close-circle-outline',
  trash: 'trash-bin-outline',
  undo: 'arrow-undo-outline',
  upload: 'cloud-upload-outline',
  wallet: 'wallet-outline',
};

export const FONTAWESOME_ICONS = {
  ban: 'ban',
  bank: 'bank',
  contact: 'address-book-o',
  copyright: 'copyright',
  diamond: 'diamond',
  dollar: 'dollar',
  id: 'id-card-o',
};

export const MATERIAL_ICONS = {
  brightness: 'brightness-4',
  device: 'devices-other',
};

export const ICONS = {
  ...IONIC_ICONS,
  ...FONTAWESOME_ICONS,
  ...MATERIAL_ICONS,
};

export const ICON_FONT_SIZE_OFFSET = 4;
